module.exports = {
  CONTACT_EMAIL:
    (process.env.NEXT_PUBLIC_CONTACT_EMAIL &&
      btoa(
        unescape(encodeURIComponent(process.env.NEXT_PUBLIC_CONTACT_EMAIL))
      )) ||
    'dGhpc2lzZXZ5QGZveG1haWwuY29t',
  CONTACT_WEIBO: process.env.NEXT_PUBLIC_CONTACT_WEIBO || '',
  CONTACT_TWITTER: process.env.NEXT_PUBLIC_CONTACT_TWITTER || '',
  CONTACT_GITHUB:
    process.env.NEXT_PUBLIC_CONTACT_GITHUB ||
    'https://github.com/1985312383',
  CONTACT_TELEGRAM: process.env.NEXT_PUBLIC_CONTACT_TELEGRAM || '',
  CONTACT_LINKEDIN: process.env.NEXT_PUBLIC_CONTACT_LINKEDIN || '',
  CONTACT_INSTAGRAM: process.env.NEXT_PUBLIC_CONTACT_INSTAGRAM || '',
  CONTACT_BILIBILI:
    process.env.NEXT_PUBLIC_CONTACT_BILIBILI ||
    'https://space.bilibili.com/40037643',
  CONTACT_YOUTUBE: process.env.NEXT_PUBLIC_CONTACT_YOUTUBE || '',
  CONTACT_XIAOHONGSHU: process.env.NEXT_PUBLIC_CONTACT_XIAOHONGSHU || '',
  CONTACT_ZHISHIXINGQIU:
    process.env.NEXT_PUBLIC_CONTACT_ZHISHIXINGQIU || '',
  CONTACT_WEHCHAT_PUBLIC:
    process.env.NEXT_PUBLIC_CONTACT_WEHCHAT_PUBLIC || ''
}
