module.exports = {
  NOTION_HOST: process.env.NEXT_PUBLIC_NOTION_HOST || 'https://www.notion.so',
  IMAGE_COMPRESS_WIDTH:
    process.env.NEXT_PUBLIC_IMAGE_COMPRESS_WIDTH || 800,
  IMAGE_ZOOM_IN_WIDTH:
    process.env.NEXT_PUBLIC_IMAGE_ZOOM_IN_WIDTH || 1200,
  IMAGE_COMPRESS_QUALITY:
    process.env.NEXT_PUBLIC_IMAGE_COMPRESS_QUALITY || 80,
  RANDOM_IMAGE_URL: process.env.NEXT_PUBLIC_RANDOM_IMAGE_URL || '',
  RANDOM_IMAGE_REPLACE_TEXT:
    process.env.NEXT_PUBLIC_RANDOM_IMAGE_NOT_REPLACE_TEXT ||
    'https://tuapi.eees.cc/api.php?category=dongman&type=302',

  IMG_LAZY_LOAD_PLACEHOLDER:
    process.env.NEXT_PUBLIC_IMG_LAZY_LOAD_PLACEHOLDER ||
    'data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==',
  IMG_URL_TYPE: process.env.NEXT_PUBLIC_IMG_TYPE || 'Notion',
  IMG_SHADOW: process.env.NEXT_PUBLIC_IMG_SHADOW || false,
  IMG_COMPRESS_WIDTH: process.env.NEXT_PUBLIC_IMG_COMPRESS_WIDTH || 800
}
